#! /usr/bin/env zsh

target=$(perl -pe 's/([a-z])([A-Z])/$1 $2/g; s/[^a-zA-Z0-9]+/ /g; s/(\w+)/\L\u$1/g; s/ //g'<<(basename $(pwd)))

>Makefile <<EOF
CXXFLAGS += $@
$target: main.cpp
	\$(LINK.cpp) \$^ \$(LOADLIBES) \$(LDLIBS) -o \$@
EOF
make -B
