#!/usr/bin/env zsh
[[ -n $1 ]]&&[[ -n $2 ]]&&diff <((( ${+TIMEOUT} ))&&timeout $TIMEOUT ${@:2} < $1||${@:2} < $1) $1:r.out||echo 'find /Volumes/Work/Downloads/taming_bronze_feb18/*.in(n) -exec cp_test {} ./taming ";"'
