#!/usr/bin/env zsh
local USAGE='find /path/to/testcases/*.in(n) -exec '"$0"' {} /path/to/binary ";"'
[[ $# < 2 ]]&&echo $USAGE||diff <((( ${+TIMEOUT} ))&&timeout $TIMEOUT ${@:2} < $1||${@:2} < $1) $1:r.out
