#!/usr/bin/env zsh
command=$1
# command is a single word (python files use shebang line)
for set in ${@:2};do
	diff <((( ${+TIMEOUT} )) && timeout $TIMEOUT $command< $set||$command< $set) $set:r.out
done
