#!/usr/bin/env zsh
setopt aliases

alias cpp="g++-13 -O2 -lm -std=c++17"

local PROBLEMNAME=${1-'PROBLEMNAME'}
local editor=${EDITOR-'vim'}
local sample_in=${${PROBLEMNAME}:r}.in
local code=${${PROBLEMNAME}:r}.${${${PROBLEMNAME}:e}:-'cpp'}

[[ -f $sample_in ]]&&$editor $code||$editor $sample_in $code
[[ ${${code}:e} = 'cpp' ]]&&cpp -o ${${code}:r} $code
#if ! diff -bqBN $code ${code}~;then
#fi
