#!/usr/bin/env zsh
setopt aliases

ERROR_MSG='Something went wrong'

alias cpp="g++-13 -O2 -lm -std=c++17"

# no idea how java works jiyang good luck

[[ -f ${PROBLEMNAME-'PROBLEMNAME'}.in ]]||${EDITOR-'vim'} ${PROBLEMNAME-'PROBLEMNAME'}.in
${EDITOR-'vim'} ${PROBLEMNAME-'PROBLEMNAME'}.cpp
cpp -o ${PROBLEMNAME-'PROBLEMNAME'} ${PROBLEMNAME-'PROBLEMNAME'}.cpp